# Generated by Django 4.1.4 on 2023-02-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0015_alter_user_calorie_goal_alter_user_carb_goal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="checkout_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="customernumber",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
